services:
  fake-gcs:
    container_name: fake-gcs
    image: "fsouza/fake-gcs-server:latest"
    command:
      - "-scheme=http"
      - "-port=4443"
      - "-public-host=localhost:4443"
    ports:
      - "4443:4443"
    volumes:
      - "./fake-gcs-data:/data"
  fake-logs:
    container_name: fake-logs
    image: mingrammer/flog
    command:
      - "--format=json"
      - "--loop"
      - --sleep=1s
    ports:
      - "9429:9429"
    volumes:
      - "./fake-logs-data:/data"
    platform: linux/amd64
  victorialogs:
    container_name: victorialogs
    image: "victoriametrics/victoria-logs:latest"
    command:
      - "-storageDataPath=/data"
    ports:
      - "9428:9428"
    volumes:
      - "./victorialogs-data:/data"
  alloy:
    depends_on:
      - victorialogs
      - fake-logs
    container_name: alloy
    image: "grafana/alloy:latest"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
  vlbackup:
    depends_on:
      - fake-gcs
      - victorialogs
      - fake-logs
      - alloy
    container_name: vlbackup
    build: ..
    command: "vlbackup --victorialogsurl=http://victorialogs:9428"
  trigger:
    depends_on:
      - vlbackup
    container_name: trigger
    image: curlimages/curl:latest
    command:
      - watch -n10 "curl -sL http://vlbackup:8080/snapshot -d'{\"\"}'"
