---
# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.7.0/configuration-schema.json
package: client
generate:
  client: true
  models: true
output: pkg/client/gen.go
