---
profile: coverage.out
threshold:
  file: 70
  package: 80
  total: 90
force-annotation-comment: true
breakdown-file-name: master.breakdown
diff:
  base-breakdown-file-name: master.breakdown
  threshold: -1
