// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// AttachResponse The outcome of attaching a partition.
type AttachResponse struct {
	// Partition The partition that was attached, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// ErrorResponse A structured error returned when a request cannot be fulfilled.
type ErrorResponse struct {
	// Code HTTP status code associated with the error
	Code *int32 `json:"code,omitempty"`

	// Error Error message describing the issue
	Error *string `json:"error,omitempty"`
}

// MigrateRequest Parameters for a migrate request.
type MigrateRequest struct {
	// Range Inclusive time range whose sealed days will be migrated
	Range TimeRange `json:"range"`

	// TargetVlAuthKey Optional auth key for the target VictoriaLogs insert/select APIs, passed as the VictoriaLogs authKey
	TargetVlAuthKey *string `json:"target_vl_auth_key,omitempty"`

	// TargetVlbackupUrl Base URL of the target vlbackup instance, used to move sealed partitions (receive/attach)
	TargetVlbackupUrl string `json:"target_vlbackup_url"`

	// TargetVlinsertUrl Base URL of the target VictoriaLogs insert API, used to ingest today's data via the JSON stream API
	TargetVlinsertUrl string `json:"target_vlinsert_url"`

	// TargetVlselectUrl Base URL of the target VictoriaLogs select API, used to verify ingested row counts after migration
	TargetVlselectUrl string `json:"target_vlselect_url"`
}

// MigrateResponse The outcome of a migrate request.
type MigrateResponse struct {
	// Errors Per-day and recent-phase error messages
	Errors []string `json:"errors"`

	// Recent The outcome of copying today's (still-open) data
	Recent *RecentMigration `json:"recent,omitempty"`

	// Skipped Sealed partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Sealed partitions (YYYYMMDD) that were successfully moved
	Transferred []string `json:"transferred"`
}

// ReceiveResponse The outcome of receiving a partition snapshot.
type ReceiveResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition The partition that was received, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// RecentMigration The outcome of copying today's data as streamed JSONLine.
type RecentMigration struct {
	// BytesIngested Number of JSONLine bytes streamed to the target insert API
	BytesIngested int64 `json:"bytes_ingested"`

	// Partition Today's partition (YYYYMMDD) whose data was copied
	Partition string `json:"partition"`

	// SourceCount Row count for today on the source, from the verification query
	SourceCount int64 `json:"source_count"`

	// TargetCount Row count for today on the target, from the verification query
	TargetCount int64 `json:"target_count"`

	// Verified True when the target row count is at least the source row count
	Verified bool `json:"verified"`
}

// RestoreRequest Parameters for a restore request.
type RestoreRequest struct {
	// PartitionPrefix Partition to restore, formatted as YYYYMMDD
	PartitionPrefix string `json:"partition_prefix"`

	// SourceUrl Object Storage source URL to restore from, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	SourceUrl string `json:"source_url"`
}

// RestoreResponse The outcome of restoring a partition snapshot.
type RestoreResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition Array of partitions restored
	Partition []string `json:"partition"`
}

// SnapshotRequest Parameters for a snapshot request.
type SnapshotRequest struct {
	// DestinationUrl Object Storage destination URL, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	DestinationUrl string `json:"destination_url"`

	// Range Inclusive time range whose days will be snapshotted
	Range TimeRange `json:"range"`
}

// TimeRange An inclusive range of time. Each bound is a time expression of the form `<anchor>[+-<duration>][/<rounding>]`, where the anchor is `now` or an RFC3339 date, the optional duration is `<int><unit>` (e.g. `-7d`, `+12h`), and the optional `/<unit>` rounds the result down to that unit. Units: `y` (year), `M` (month), `w` (week, starts Monday), `d` (day), `h` (hour), `m` (minute), `s` (second). All math is performed in UTC.
type TimeRange struct {
	// From Start of the range, inclusive. A relative or absolute time expression (e.g. `now-7d/d`, `2024-01-01T00:00:00Z`).
	From string `json:"from"`

	// To End of the range, inclusive. A relative or absolute time expression (e.g. `now/d`, `2024-01-15T00:00:00Z`). Defaults to now.
	To *string `json:"to,omitempty"`
}

// TransferRequest Parameters for a transfer request.
type TransferRequest struct {
	// Range Inclusive time range whose days will be transferred
	Range TimeRange `json:"range"`

	// TargetUrl Base URL of the target vlbackup instance to transfer partitions to
	TargetUrl string `json:"target_url"`
}

// TransferResponse The outcome of a transfer request, per day.
type TransferResponse struct {
	// Errors Per-day error messages for partitions that failed to transfer
	Errors []string `json:"errors"`

	// Skipped Partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Partitions (YYYYMMDD) that were successfully transferred
	Transferred []string `json:"transferred"`
}

// PartitionQueryParam defines model for PartitionQueryParam.
type PartitionQueryParam = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AttachSnapshotParams defines parameters for AttachSnapshot.
type AttachSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// ReceiveSnapshotParams defines parameters for ReceiveSnapshot.
type ReceiveSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// MigratePartitionsJSONRequestBody defines body for MigratePartitions for application/json ContentType.
type MigratePartitionsJSONRequestBody = MigrateRequest

// RestoreSnapshotJSONRequestBody defines body for RestoreSnapshot for application/json ContentType.
type RestoreSnapshotJSONRequestBody = RestoreRequest

// TriggerSnapshotJSONRequestBody defines body for TriggerSnapshot for application/json ContentType.
type TriggerSnapshotJSONRequestBody = SnapshotRequest

// TransferPartitionsJSONRequestBody defines body for TransferPartitions for application/json ContentType.
type TransferPartitionsJSONRequestBody = TransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Migrate partitions and recent data to another vlbackup instance
	// (POST /v1/vlbackup/migrate)
	MigratePartitions(w http.ResponseWriter, r *http.Request)
	// Restore a partition from Object Storage
	// (POST /v1/vlbackup/restore)
	RestoreSnapshot(w http.ResponseWriter, r *http.Request)
	// Snapshot a range of partitions to Object Storage
	// (POST /v1/vlbackup/snapshot)
	TriggerSnapshot(w http.ResponseWriter, r *http.Request)
	// Transfer partitions to another vlbackup instance
	// (POST /v1/vlbackup/transfer)
	TransferPartitions(w http.ResponseWriter, r *http.Request)
	// Attach a received partition to VictoriaLogs
	// (POST /v1/vlbackup/transfer/attach)
	AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams)
	// Receive a snapshot from another vlbackup instance
	// (POST /v1/vlbackup/transfer/receive)
	ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Migrate partitions and recent data to another vlbackup instance
// (POST /v1/vlbackup/migrate)
func (_ Unimplemented) MigratePartitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore a partition from Object Storage
// (POST /v1/vlbackup/restore)
func (_ Unimplemented) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Snapshot a range of partitions to Object Storage
// (POST /v1/vlbackup/snapshot)
func (_ Unimplemented) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transfer partitions to another vlbackup instance
// (POST /v1/vlbackup/transfer)
func (_ Unimplemented) TransferPartitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Attach a received partition to VictoriaLogs
// (POST /v1/vlbackup/transfer/attach)
func (_ Unimplemented) AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Receive a snapshot from another vlbackup instance
// (POST /v1/vlbackup/transfer/receive)
func (_ Unimplemented) ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// MigratePartitions operation middleware
func (siw *ServerInterfaceWrapper) MigratePartitions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MigratePartitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreSnapshot operation middleware
func (siw *ServerInterfaceWrapper) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreSnapshot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSnapshot operation middleware
func (siw *ServerInterfaceWrapper) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSnapshot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferPartitions operation middleware
func (siw *ServerInterfaceWrapper) TransferPartitions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferPartitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachSnapshot operation middleware
func (siw *ServerInterfaceWrapper) AttachSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AttachSnapshotParams

	// ------------- Required query parameter "partition" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "partition", r.URL.Query(), &params.Partition, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "partition"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partition", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveSnapshot operation middleware
func (siw *ServerInterfaceWrapper) ReceiveSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveSnapshotParams

	// ------------- Required query parameter "partition" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "partition", r.URL.Query(), &params.Partition, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "partition"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partition", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/migrate", wrapper.MigratePartitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/restore", wrapper.RestoreSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/snapshot", wrapper.TriggerSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer", wrapper.TransferPartitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer/attach", wrapper.AttachSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer/receive", wrapper.ReceiveSnapshot)
	})

	return r
}

type MigratePartitionsRequestObject struct {
	Body *MigratePartitionsJSONRequestBody
}

type MigratePartitionsResponseObject interface {
	VisitMigratePartitionsResponse(w http.ResponseWriter) error
}

type MigratePartitions200JSONResponse MigrateResponse

func (response MigratePartitions200JSONResponse) VisitMigratePartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type MigratePartitions400JSONResponse ErrorResponse

func (response MigratePartitions400JSONResponse) VisitMigratePartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type MigratePartitions500JSONResponse MigrateResponse

func (response MigratePartitions500JSONResponse) VisitMigratePartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshotRequestObject struct {
	Body *RestoreSnapshotJSONRequestBody
}

type RestoreSnapshotResponseObject interface {
	VisitRestoreSnapshotResponse(w http.ResponseWriter) error
}

type RestoreSnapshot202JSONResponse RestoreResponse

func (response RestoreSnapshot202JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot400JSONResponse ErrorResponse

func (response RestoreSnapshot400JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot404JSONResponse ErrorResponse

func (response RestoreSnapshot404JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot409JSONResponse ErrorResponse

func (response RestoreSnapshot409JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot500JSONResponse ErrorResponse

func (response RestoreSnapshot500JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSnapshotRequestObject struct {
	Body *TriggerSnapshotJSONRequestBody
}

type TriggerSnapshotResponseObject interface {
	VisitTriggerSnapshotResponse(w http.ResponseWriter) error
}

type TriggerSnapshot202Response struct {
}

func (response TriggerSnapshot202Response) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerSnapshot400JSONResponse ErrorResponse

func (response TriggerSnapshot400JSONResponse) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSnapshot500JSONResponse ErrorResponse

func (response TriggerSnapshot500JSONResponse) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitionsRequestObject struct {
	Body *TransferPartitionsJSONRequestBody
}

type TransferPartitionsResponseObject interface {
	VisitTransferPartitionsResponse(w http.ResponseWriter) error
}

type TransferPartitions200JSONResponse TransferResponse

func (response TransferPartitions200JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitions400JSONResponse ErrorResponse

func (response TransferPartitions400JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitions500JSONResponse TransferResponse

func (response TransferPartitions500JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshotRequestObject struct {
	Params AttachSnapshotParams
}

type AttachSnapshotResponseObject interface {
	VisitAttachSnapshotResponse(w http.ResponseWriter) error
}

type AttachSnapshot200JSONResponse AttachResponse

func (response AttachSnapshot200JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot400JSONResponse ErrorResponse

func (response AttachSnapshot400JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot401JSONResponse ErrorResponse

func (response AttachSnapshot401JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot500JSONResponse ErrorResponse

func (response AttachSnapshot500JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshotRequestObject struct {
	Params ReceiveSnapshotParams
	Body   io.Reader
}

type ReceiveSnapshotResponseObject interface {
	VisitReceiveSnapshotResponse(w http.ResponseWriter) error
}

type ReceiveSnapshot200JSONResponse ReceiveResponse

func (response ReceiveSnapshot200JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot400JSONResponse ErrorResponse

func (response ReceiveSnapshot400JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot401JSONResponse ErrorResponse

func (response ReceiveSnapshot401JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot409JSONResponse ErrorResponse

func (response ReceiveSnapshot409JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot500JSONResponse ErrorResponse

func (response ReceiveSnapshot500JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Migrate partitions and recent data to another vlbackup instance
	// (POST /v1/vlbackup/migrate)
	MigratePartitions(ctx context.Context, request MigratePartitionsRequestObject) (MigratePartitionsResponseObject, error)
	// Restore a partition from Object Storage
	// (POST /v1/vlbackup/restore)
	RestoreSnapshot(ctx context.Context, request RestoreSnapshotRequestObject) (RestoreSnapshotResponseObject, error)
	// Snapshot a range of partitions to Object Storage
	// (POST /v1/vlbackup/snapshot)
	TriggerSnapshot(ctx context.Context, request TriggerSnapshotRequestObject) (TriggerSnapshotResponseObject, error)
	// Transfer partitions to another vlbackup instance
	// (POST /v1/vlbackup/transfer)
	TransferPartitions(ctx context.Context, request TransferPartitionsRequestObject) (TransferPartitionsResponseObject, error)
	// Attach a received partition to VictoriaLogs
	// (POST /v1/vlbackup/transfer/attach)
	AttachSnapshot(ctx context.Context, request AttachSnapshotRequestObject) (AttachSnapshotResponseObject, error)
	// Receive a snapshot from another vlbackup instance
	// (POST /v1/vlbackup/transfer/receive)
	ReceiveSnapshot(ctx context.Context, request ReceiveSnapshotRequestObject) (ReceiveSnapshotResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// MigratePartitions operation middleware
func (sh *strictHandler) MigratePartitions(w http.ResponseWriter, r *http.Request) {
	var request MigratePartitionsRequestObject

	var body MigratePartitionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MigratePartitions(ctx, request.(MigratePartitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MigratePartitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MigratePartitionsResponseObject); ok {
		if err := validResponse.VisitMigratePartitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestoreSnapshot operation middleware
func (sh *strictHandler) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {
	var request RestoreSnapshotRequestObject

	var body RestoreSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestoreSnapshot(ctx, request.(RestoreSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestoreSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestoreSnapshotResponseObject); ok {
		if err := validResponse.VisitRestoreSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSnapshot operation middleware
func (sh *strictHandler) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {
	var request TriggerSnapshotRequestObject

	var body TriggerSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSnapshot(ctx, request.(TriggerSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSnapshotResponseObject); ok {
		if err := validResponse.VisitTriggerSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferPartitions operation middleware
func (sh *strictHandler) TransferPartitions(w http.ResponseWriter, r *http.Request) {
	var request TransferPartitionsRequestObject

	var body TransferPartitionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TransferPartitions(ctx, request.(TransferPartitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferPartitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TransferPartitionsResponseObject); ok {
		if err := validResponse.VisitTransferPartitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AttachSnapshot operation middleware
func (sh *strictHandler) AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams) {
	var request AttachSnapshotRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AttachSnapshot(ctx, request.(AttachSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AttachSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AttachSnapshotResponseObject); ok {
		if err := validResponse.VisitAttachSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveSnapshot operation middleware
func (sh *strictHandler) ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams) {
	var request ReceiveSnapshotRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveSnapshot(ctx, request.(ReceiveSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveSnapshotResponseObject); ok {
		if err := validResponse.VisitReceiveSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7c9u2lv8qGO6dudKG1sNWHtb+0XGadja7dpPaTmdS2xtB5JGImgRYALSiJv7uOwcA35QiN47r7t5O",
	"Z6wHCBycxw/n/A6UT14gklRw4Fp5009eSiVNQIM0795SqZlmgv+cgVy/xe/w4xBUIFmKX3jTchDhNAGi",
	"BREpSKqBCO6ThZAJ1RpCQhV5//79+5OTV68832P46O84red7+KA3xcXtTJ7vSfg9YxJCb6plBr6ngggS",
	"iqvDR5qkMY7fH+1PRuPxU8/3EvrxGPhSR970he8ljFfepbi+xPX+5/Iy/PTi9h+e7+l1ilMoLRlfere3",
	"t/kSZuNHWtMgOgWVCq6gvefzCIjIdCASIGJBqBnO+JJQUmxi4PleKlEXmkGuXLe/zgmLr4mOqCYrqtzE",
	"EG7W47fRRlX/FxW5r4qhYv4bBNq79b0fpBRys6qOiNIyC3QmISSAY4kEnUkOIVlFwAkluBYoTQLKudBk",
	"DmSRxQsWxxC2lRiIsGOV/zw/f0uUpjpTBEcQqpQIGEWFrZiOiI7Aru75ntWlN/UY1wf7Vl8syRJv+vTw",
	"0OjLvhuPRsV+GdewBIkbttO0RDB6IAkoRZdA7Hdz9AlcmimVQd0yk9Hhs5pxxjXjXFxeqsvLs6t/77ZP",
	"ywwnbIlBd2p12RmmLrLRlwgliX0g135b05LypVE1jeM3C2968cn7h4SFN/X+bViixtCFzfCcJXBqHrm9",
	"8huLv+ZBnCl2A0SzBIiZmawioYAooDGEJKRrRVYsjtH8TrQQ96WpXIL+cBN/oJmOPlzDur23N+YFjQkO",
	"IdewNltEvdunyS8s0EIyeiyWijCuQOqhghgCTY7evlY+SalSNrbwqdpwnPO/YV033v5o8mJnc1U2MafB",
	"dZZ+yGTc3sVLqoC8Oz1GRKnInj+EcmvKA/BJhrJqQRJxUyiwCFJFehICYDcwtPDRr8FEpHU6HQ7t5Hv5",
	"5NMXoxejamighB07rrvr5n1aHd9pnx02QuOUu2V8iSihRUjX/1QkpJqSG0bNHP919uYnBBqgCT60dcd2",
	"7unhZP/FPe7YutOf33HpjuWOb0CyxdptHEIixYoEIuNaEbrQIF2g2BNz84bt1Pey4cbJ0OXX3V7QrSnf",
	"gczVNkDb9RD+MqIZ5FYd2AhyL6RrQnlIMHa43ksjtBlUMV1h2qIhMRPcD5Ab9b+2c45H+F8xhEpJ157R",
	"Nwq0Ow6fmvEnhWe00bihuECka3NOucDqKc3ieE+kwPsmylAKdc3SFI3e1N1ZG37y9KTvEhmQQNzzPoHB",
	"ckASphQuiQdRLIGGa5JKUMA1MelPHiIbNP6nkppddK0l5WoBUn7NTrMgAKUWWRyvDUKHD7uLZohWtlSa",
	"0c9joSvyTu3xsXPk2eOmkf4SxWmqItERhvO1BvVhJZnW0JEL/5Qlc5A4sRlI3EAExJCpa7KKWAwEPmpJ",
	"A50nWPlqjfTu2aSa3h2ORs/Hh4f7TyfPJ6PDw3El1+vM9O6esLuT99Ek7H5D2ZvMXQWML5m7iRfmIKbK",
	"Hb8QmsP4mHHYZPn8PNtm+nwO5wPF3FpUT9AyTXgwu7tNl7avgIDNaI0+0BkCkTIba9/C5r6nRCYD+GAy",
	"grakp3myYJNhlDsHV/ugTxZSJOYDk2iwwNif5FX5/enTHf13F9Q++HCC2um7PPNcZmDr1Yr7FfkYYVir",
	"kxgoJqiFhssBpfnmQsRA+Q4xW4RJw9INfVak7o5upYW8Q10o7QObs6hC0g+phAX7uI0S0iKf74ERsdBZ",
	"Z0L+xqiHnGkhsVh31sIMvRTYOJ3LV5ZqOhzOs+Aa9NBueoi5izpofVzbj3ksWe+5IXmaPLznLLyyU79t",
	"na1OsfMJj+P/f53wR5hOoYyVhM+5Rg3TL6pu614+Q60XOd+OmYOd+sHjZGv2eLdM4syZaHewyY26GW1C",
	"UJpxA/g7xXJlPAb04wxg/4HItRqrluvaEGsNOze1vK0wL2VpxwwnrJDGCiIWRqwB+YEGEZmLjIfmtLTC",
	"wkes+xQay3EjqFcyu8xGo4OA8iAS0ryGiyd79sMws3mq/fjqYmg/ljgz40v38czH01qCmdPOg8vOuFjN",
	"TNnJyemP3x8cHBxivga+GSdyHjFfwzxi52dc26nt24wz935GesbFZnvPw5lPZk/G+9Gs7xsyoTbpbNh+",
	"1EhtSUcJKos1CcWK2yyXaoJDB+QdZ1pNyWw9I701UNn3yexkRnqJ4DrCN6sZ6a0Arn2iNJVakRPBQ7rG",
	"r8IZ6bmX0Yz0IpGZxxN8nPFMA75TM9JTEAge9gfkKI5JQnWEe09Boj0gJIyTd+fft8MTD8mOUhnFyC1q",
	"/MAvHWNAjoiEmGp0EjTFXIk409DyCKdXLlZ7z8OhUS4i395ovDcan49GU/P/r7P+oBa0+fh6VD6b1GLy",
	"oAaPPS5WnxEjJ7d7+Gc//3Nu/0xrf3qXl4PLy/BJ/7ver58vnuxd1b7t93uXl58vLz/3v+u5L59crE9W",
	"YZSoq/53vWHlTTcgi47mAg/vUZ11XY6f1nRJXsGCZrFW6IVcrFrK/btqtgF5xnM78c0xJrufYjnH8lf3",
	"UmpwXyV+yhrsqzoPBpfyvVbSIi0eqsXQzT9/8cQqLLozl9w0qY9YiAq+O6tcJ5GNy1R1hzi/oCx25IZb",
	"96/hmjeyvG//79O7b+/C69ZZ1b8Ru4tGhiCTTK/PEGxcvQZUgjzKUNQWOJjviBbXwDExsBcd0IiB4Au2",
	"NI39IlzyDqzn7lMYysPMUO4W8cFeuWB80XHYHb19bfUeUR7GoMrMlfGlX+re1KOmZZNXp7WOWhlkGLOa",
	"aQNOvxy/tKBmScMbkMquOh6MBiM0gUiB05R5U+9gMBocmJpaR0ZPw5txWQS4dpOhRETXOXHMrksY9sk8",
	"04TGSuR9Kpv2JUJp13Rqd14G5EchCWDmXPbJMRezCaNBJgjdGcC0aTfYadMqBdOF6b1cqb4jV30SgqZB",
	"5LtbJ/0BeW3ILG6JTFUnfOdry7/lzhCLgMZ1A4gbkARf/XzcyQ8b41mWC2dhmjBek/afqtnYHZDzqhAs",
	"J1lJr8K6MUViWJjZaKD71WVsSk/1nqHq9gQPYGo4rz2ZcfxjGeVyr1KslE8Uw9OvtrlQgCJcaBJCmKUx",
	"C+yNJ7cQepy9BsUEfx1607ydWaKMu+QESr8U4dpebeE6b/Wldkom+PA3ZemJ8grUttShcQ/EhFndLU/q",
	"bVJSufPVvHdl0Maemcb/90ejHQQtMoHybLy4qjYym22AyfhwcjCa1OiYKslRJ7rHo/1Jk1O2n5X0rRO+",
	"OM8KkmbfYGL1HCi+Oij5m4l3devfVeEut9iocXQ+fD6G4lYSFySi0t2LUgg+k500vJtk9ZtZHXK9pGGZ",
	"39iTm8au4JuLcI1Vxg2NWY4wWEO7DxycvDs9Rqmf3qPUO+jzDTeyJEK6nNfd9nG9ewMNtoFvE6v/yAts",
	"MyOJmdKmtm00/QszoO2zJKFyXQmXSs5WecSspQWhXOgIZDtnNnT9UlUPa+8KV6idJY7923yWvBIrHgsa",
	"qk4GlvQoWmSw/KNf9kocGjb4MUtl+Tm7qmqwa0Hc6o/qyGzU3UE0A7WogWAb5RyxfFZytd8C4xo9jQ4P",
	"Oa03Me6Gcft3w7gG2b0dzHaGlSZF37HJs5I8tdxx1V5hLWF9dNCCIZtxlaWpkAiHlRaMyxuNxJOHk/i8",
	"llIVkbWi9phfWOaSN+LJinn4cGJ+L/giZoH2G2kepjWu1io8wISzNf7ThzT+a46VDo2JAok5oK2AbVcn",
	"dEDm6sMyd6/1eOoQnEdzFfoMzDVsUUJtjqdtpC2W2Ai1u6fcPgkkmEyeNi7z5d7jCBWLq4XwecptMJUa",
	"MtyAd56rV3sYG+AbIz0ETCVUZYVqR64OzOeSLZcgvzEwNxtA20Hrz0LzFyakQQCphtC1HDqsaCkzqqot",
	"EaPRLEXXxITBpBWRiI2fcuEuuZRMB+lRTiBJ9TqvvjAtcJ/Q4JqLVQzhEhLguj949PDb6JpVMPjRAIcJ",
	"NYca1k5fQI3CMWjZiqqRlpvho5ixjR9FEncv+JEvpL4IE91lfF602/TM4b1NA9S1qj6BOao5FwjrhAe7",
	"q29enjbJ9a6DuEG9PliB+hDVYouK3qaAf1WL96LPVrnYptu3VoidZeF5Zx/ka+vA/Cv3043NIHOUV2WU",
	"pBJumMhUvC6un7bpvw56LpesjQZ28kquUP1Z4IbWVTlk2PWzwdurr43UryunGr/o6/CS8tLaI6ygKh2V",
	"PKZKfRjJxg8n2TtOMx0Jyf6AsFM0S/iXvYDHlEaUv9Ws1U+1zohx8mpP5OIK/bcMfutNhjjuCrhqmN0x",
	"7t2EmwPfXc6vFA2OHTdtyw5qyBRKG2HJ5Aq7cEE+scWlFmQORYh0MUBGvm8AHrskI8s/WFp3pHaRj2Mw",
	"g9dUEiqDyNybWDTK6UJ9IZOA1qxdNJ4zTmXjJ4Hj0eHh0/H42f7z58+ffamN3ck+VAUrjdot1/1nQt+K",
	"xqr/lmR7ReiCqeKTj5DH2gLFvml5k0BImaXaGfFvgc+PgsPKCSz4aPIvc1eAlYnKozpHNt1OvtM54qKj",
	"ehF2O1xvOE3MmiiihdjuXXi+uXJT3M8xAB8Jpe3NHJTMzb2RYtnQX++spd0/6lAqxv+0qc4pq+A56BUA",
	"b29clTMWG2/PmBOFm+Q0yi1WK6fM6cLbq9v/DQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
