// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// AttachResponse The outcome of attaching a partition.
type AttachResponse struct {
	// Partition The partition that was attached, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// ErrorResponse A structured error returned when a request cannot be fulfilled.
type ErrorResponse struct {
	// Code HTTP status code associated with the error
	Code *int32 `json:"code,omitempty"`

	// Error Error message describing the issue
	Error *string `json:"error,omitempty"`
}

// ReceiveResponse The outcome of receiving a partition snapshot.
type ReceiveResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition The partition that was received, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// RestoreRequest Parameters for a restore request.
type RestoreRequest struct {
	// PartitionPrefix Partition to restore, formatted as YYYYMMDD
	PartitionPrefix string `json:"partition_prefix"`

	// SourceUrl Object Storage source URL to restore from, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	SourceUrl string `json:"source_url"`
}

// RestoreResponse The outcome of restoring a partition snapshot.
type RestoreResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition The partition that was restored, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// TransferRange An inclusive range of time. Each bound is a time expression of the form `<anchor>[+-<duration>][/<rounding>]`, where the anchor is `now` or an RFC3339 date, the optional duration is `<int><unit>` (e.g. `-7d`, `+12h`), and the optional `/<unit>` rounds the result down to that unit. Units: `y` (year), `M` (month), `w` (week, starts Monday), `d` (day), `h` (hour), `m` (minute), `s` (second). All math is performed in UTC.
type TransferRange struct {
	// From Start of the range, inclusive. A relative or absolute time expression (e.g. `now-7d/d`, `2024-01-01T00:00:00Z`).
	From string `json:"from"`

	// To End of the range, inclusive. A relative or absolute time expression (e.g. `now/d`, `2024-01-15T00:00:00Z`). Defaults to now.
	To *string `json:"to,omitempty"`
}

// TransferRequest Parameters for a transfer request.
type TransferRequest struct {
	// Range Inclusive time range whose days will be transferred
	Range TransferRange `json:"range"`

	// TargetUrl Base URL of the target vlbackup instance to transfer partitions to
	TargetUrl string `json:"target_url"`
}

// TransferResponse The outcome of a transfer request, per day.
type TransferResponse struct {
	// Errors Per-day error messages for partitions that failed to transfer
	Errors []string `json:"errors"`

	// Skipped Partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Partitions (YYYYMMDD) that were successfully transferred
	Transferred []string `json:"transferred"`
}

// TriggerRequest Parameters for a snapshot request.
type TriggerRequest struct {
	// DestinationUrl Object Storage destination URL, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	DestinationUrl string `json:"destination_url"`

	// PartitionPrefix Partition to snapshot, formatted as YYYYMMDD. Defaults to yesterday (UTC).
	PartitionPrefix *string `json:"partition_prefix,omitempty"`
}

// PartitionQueryParam defines model for PartitionQueryParam.
type PartitionQueryParam = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AttachSnapshotParams defines parameters for AttachSnapshot.
type AttachSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// ReceiveSnapshotParams defines parameters for ReceiveSnapshot.
type ReceiveSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// RestoreSnapshotJSONRequestBody defines body for RestoreSnapshot for application/json ContentType.
type RestoreSnapshotJSONRequestBody = RestoreRequest

// TriggerSnapshotJSONRequestBody defines body for TriggerSnapshot for application/json ContentType.
type TriggerSnapshotJSONRequestBody = TriggerRequest

// TransferPartitionsJSONRequestBody defines body for TransferPartitions for application/json ContentType.
type TransferPartitionsJSONRequestBody = TransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Restore a partition from Object Storage
	// (POST /v1/vlbackup/restore)
	RestoreSnapshot(w http.ResponseWriter, r *http.Request)
	// Snapshot a partition to Object Storage
	// (POST /v1/vlbackup/snapshot)
	TriggerSnapshot(w http.ResponseWriter, r *http.Request)
	// Transfer partitions to another vlbackup instance
	// (POST /v1/vlbackup/transfer)
	TransferPartitions(w http.ResponseWriter, r *http.Request)
	// Attach a received partition to VictoriaLogs
	// (POST /v1/vlbackup/transfer/attach)
	AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams)
	// Receive a snapshot from another vlbackup instance
	// (POST /v1/vlbackup/transfer/receive)
	ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Restore a partition from Object Storage
// (POST /v1/vlbackup/restore)
func (_ Unimplemented) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Snapshot a partition to Object Storage
// (POST /v1/vlbackup/snapshot)
func (_ Unimplemented) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transfer partitions to another vlbackup instance
// (POST /v1/vlbackup/transfer)
func (_ Unimplemented) TransferPartitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Attach a received partition to VictoriaLogs
// (POST /v1/vlbackup/transfer/attach)
func (_ Unimplemented) AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Receive a snapshot from another vlbackup instance
// (POST /v1/vlbackup/transfer/receive)
func (_ Unimplemented) ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RestoreSnapshot operation middleware
func (siw *ServerInterfaceWrapper) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreSnapshot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSnapshot operation middleware
func (siw *ServerInterfaceWrapper) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSnapshot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferPartitions operation middleware
func (siw *ServerInterfaceWrapper) TransferPartitions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferPartitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachSnapshot operation middleware
func (siw *ServerInterfaceWrapper) AttachSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AttachSnapshotParams

	// ------------- Required query parameter "partition" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "partition", r.URL.Query(), &params.Partition, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "partition"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partition", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveSnapshot operation middleware
func (siw *ServerInterfaceWrapper) ReceiveSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveSnapshotParams

	// ------------- Required query parameter "partition" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "partition", r.URL.Query(), &params.Partition, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "partition"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partition", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/restore", wrapper.RestoreSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/snapshot", wrapper.TriggerSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer", wrapper.TransferPartitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer/attach", wrapper.AttachSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer/receive", wrapper.ReceiveSnapshot)
	})

	return r
}

type RestoreSnapshotRequestObject struct {
	Body *RestoreSnapshotJSONRequestBody
}

type RestoreSnapshotResponseObject interface {
	VisitRestoreSnapshotResponse(w http.ResponseWriter) error
}

type RestoreSnapshot202JSONResponse RestoreResponse

func (response RestoreSnapshot202JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot400JSONResponse ErrorResponse

func (response RestoreSnapshot400JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot404JSONResponse ErrorResponse

func (response RestoreSnapshot404JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot409JSONResponse ErrorResponse

func (response RestoreSnapshot409JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot500JSONResponse ErrorResponse

func (response RestoreSnapshot500JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSnapshotRequestObject struct {
	Body *TriggerSnapshotJSONRequestBody
}

type TriggerSnapshotResponseObject interface {
	VisitTriggerSnapshotResponse(w http.ResponseWriter) error
}

type TriggerSnapshot202Response struct {
}

func (response TriggerSnapshot202Response) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerSnapshot400JSONResponse ErrorResponse

func (response TriggerSnapshot400JSONResponse) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSnapshot500JSONResponse ErrorResponse

func (response TriggerSnapshot500JSONResponse) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitionsRequestObject struct {
	Body *TransferPartitionsJSONRequestBody
}

type TransferPartitionsResponseObject interface {
	VisitTransferPartitionsResponse(w http.ResponseWriter) error
}

type TransferPartitions200JSONResponse TransferResponse

func (response TransferPartitions200JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitions400JSONResponse ErrorResponse

func (response TransferPartitions400JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitions500JSONResponse TransferResponse

func (response TransferPartitions500JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshotRequestObject struct {
	Params AttachSnapshotParams
}

type AttachSnapshotResponseObject interface {
	VisitAttachSnapshotResponse(w http.ResponseWriter) error
}

type AttachSnapshot200JSONResponse AttachResponse

func (response AttachSnapshot200JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot400JSONResponse ErrorResponse

func (response AttachSnapshot400JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot401JSONResponse ErrorResponse

func (response AttachSnapshot401JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot500JSONResponse ErrorResponse

func (response AttachSnapshot500JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshotRequestObject struct {
	Params ReceiveSnapshotParams
	Body   io.Reader
}

type ReceiveSnapshotResponseObject interface {
	VisitReceiveSnapshotResponse(w http.ResponseWriter) error
}

type ReceiveSnapshot200JSONResponse ReceiveResponse

func (response ReceiveSnapshot200JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot400JSONResponse ErrorResponse

func (response ReceiveSnapshot400JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot401JSONResponse ErrorResponse

func (response ReceiveSnapshot401JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot409JSONResponse ErrorResponse

func (response ReceiveSnapshot409JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot500JSONResponse ErrorResponse

func (response ReceiveSnapshot500JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Restore a partition from Object Storage
	// (POST /v1/vlbackup/restore)
	RestoreSnapshot(ctx context.Context, request RestoreSnapshotRequestObject) (RestoreSnapshotResponseObject, error)
	// Snapshot a partition to Object Storage
	// (POST /v1/vlbackup/snapshot)
	TriggerSnapshot(ctx context.Context, request TriggerSnapshotRequestObject) (TriggerSnapshotResponseObject, error)
	// Transfer partitions to another vlbackup instance
	// (POST /v1/vlbackup/transfer)
	TransferPartitions(ctx context.Context, request TransferPartitionsRequestObject) (TransferPartitionsResponseObject, error)
	// Attach a received partition to VictoriaLogs
	// (POST /v1/vlbackup/transfer/attach)
	AttachSnapshot(ctx context.Context, request AttachSnapshotRequestObject) (AttachSnapshotResponseObject, error)
	// Receive a snapshot from another vlbackup instance
	// (POST /v1/vlbackup/transfer/receive)
	ReceiveSnapshot(ctx context.Context, request ReceiveSnapshotRequestObject) (ReceiveSnapshotResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RestoreSnapshot operation middleware
func (sh *strictHandler) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {
	var request RestoreSnapshotRequestObject

	var body RestoreSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestoreSnapshot(ctx, request.(RestoreSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestoreSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestoreSnapshotResponseObject); ok {
		if err := validResponse.VisitRestoreSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSnapshot operation middleware
func (sh *strictHandler) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {
	var request TriggerSnapshotRequestObject

	var body TriggerSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSnapshot(ctx, request.(TriggerSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSnapshotResponseObject); ok {
		if err := validResponse.VisitTriggerSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferPartitions operation middleware
func (sh *strictHandler) TransferPartitions(w http.ResponseWriter, r *http.Request) {
	var request TransferPartitionsRequestObject

	var body TransferPartitionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TransferPartitions(ctx, request.(TransferPartitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferPartitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TransferPartitionsResponseObject); ok {
		if err := validResponse.VisitTransferPartitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AttachSnapshot operation middleware
func (sh *strictHandler) AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams) {
	var request AttachSnapshotRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AttachSnapshot(ctx, request.(AttachSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AttachSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AttachSnapshotResponseObject); ok {
		if err := validResponse.VisitAttachSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveSnapshot operation middleware
func (sh *strictHandler) ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams) {
	var request ReceiveSnapshotRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveSnapshot(ctx, request.(ReceiveSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveSnapshotResponseObject); ok {
		if err := validResponse.VisitReceiveSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9s28v8qO/z3hfwPLVG2Ese6Fx0naecyk1xzjtOZ1NJVELkSUZMAC4BW1MTf/WYBPoqUY7dJxp25",
	"TGYskuBisQ8/7P7Aj14o00wKFEZ7049exhRL0aCyV2+YMtxwKf6do9q+oWd0O0IdKp7RA29aDwLBUgQj",
	"QWaomEGQwoeVVCkzBiNgGt6/f//+9esXLzzf4/Tq7yTW8z160ZvS5E6S53sKf8+5wsibGpWj7+kwxpTR",
	"7PiBpVlC44+Co0kwHj/2fC9lH16hWJvYmz71vZSLxlVG8yua7z+zWfTx6c13nu+ZbUYitFFcrL2bm5ty",
	"CrvwM2NYGJ+jzqTQ2F3zRYwgcxPKFEGugNnhXKyBQbWIoed7mSJbGI6lcYv19QqsHoOJmYEN04VgjPbb",
	"8etYo2n/y4be82qoXP6GofFufO8HpaTab6oz0EblockVRoA0FhSaXAmMYBOjAAY0F2oDIRNCGlgirPJk",
	"xZMEo64RQxn1zPLPi4s3oA0zuQYaAUxrGXJGBttwE4OJ0c3u+Z6zpTf1uDDHR85ePM1Tb/r49NTay12N",
	"g6BaLxcG16howU5MRwVrB0hRa7ZGcM+WFBM0Ndc6x7ZnJsHpk5Zzxi3nXM5mejZ7O///fv903HCOIfJr",
	"vHPMKjt+J2ZBC5bpWJqu3Zdbg/rXjeLGYE8A/ytPl6hIsB0IxUCCg4jrK9jEPEHAD0ax0JRWKWfb8cmT",
	"SdMnp0FwMj49PXo8OZkEp6fjhoN63XP/LHOmeDhZ5u8Ye97rbm2kwnOXOr2oXAA5LcommX2hTLZb0OnX",
	"TOGKf7gN6Y0s5X1jm/melrkK8ddcJV0Ff7LmgbdGKspBNxTenb9qKAwrJVMfcLgewlpPR6NlHl6hGblF",
	"j0Aq0Med26312NfS7WEx5DpZsvAqz0bNMCb9Wss9CiZPd9P99oBorNTveufWoLgzBtD4/2GAxQBrur8V",
	"BlwoJvQK1TkT676dVwAXYZJrfo2gaAy5xvAUh/ADC2NYylxEwDUwexfwQ6ZQa7ILDYzR2gIWszwIjkMm",
	"wlgq+xsvHx26m1GuGE3nbs8vR+62IslcrIvbC5+2eoVWppND0y6E3Cwo4ZiA8x+fHx8fn0LEDPp2nLTr",
	"YAmUc9hXnHwujBPtLnPBi+sFDGxmLw5PooUPi0fjo3hx4AMTUVvoYtR91Wqt7TiFOk8MRHJjw9eGCQ0d",
	"wjvBjZ7CYruAwRaZOvBh8XoBg1QKE9PFZgGDDeKVT/WIMhpeSxGxLT2KFjAofsYLGMQyt6+n9DoXuUG6",
	"0gsYaAyliA6GcJYkkDIT09ozVOQPjIALeHfxvJufBG3dOHhLapQetXHg14ExhDNQmDBDQUKuWGqZ5AY7",
	"EVHYVcjN4Uk0ssalPDgMxofB+CIIpvb/L4uDYStXyvHtXHkyaSXLcStZBkJuPlHGTG4O6c9R+efC/Zm2",
	"/gxms+FsFj06+H7wy6fLR4fz1tODg8Fs9mk2+3Tw/aB4+Ohy+3oTxameH3w/GDUuercbI3sqPRF9QXO2",
	"bTl+3LIlvMAVyxOjKQqF3HSM+3e17A7w2ci9FePuXOiY4o39lY4q8ZIlyU8rb3r50ftO4cqbev83qtvh",
	"UdEPjtowezP3dzR4WYGsdbJD2k0sNULEtho2PEmoqSkVoyVTZDG1RtNfyDxj2tUtRZi5sVBWGsCFNkyE",
	"ttuu1lttHhQsrTiJjcmmo5GTclhKmT4NngZfuGZpLMov7Hy7V+/aYXfc6hMekoG7/rUNmu4JFVSHEdsW",
	"XWjRqbmwadqOsH7FeIJR07ye73GDqRX7Zbo4a+qXTuY4oH/VEKYU29pq94pnGZl2by2uYVAWKQdFOUM7",
	"bfFiUeimXGsquChBEoUs2gIhEQoDtggqI2zPIv9kqf755TVT4v5LzMMQtV7lSbJtJdc3XcRuArT0KN3n",
	"lzHZnwx8vb4PwpUl836Ei1AbLmzVdKdOqTGeYOdhtkf+fVvU0k57avr25rpFbVARPAzeXTzfqWK+XsW/",
	"66lugBAKYJgrbrZvaUcqWjFkCtVZTjN3dg/7DIy8QkHVo6MmKctDKVZ8bam4Ck9ZbmK4wq1XMKA0t5Ne",
	"K08biCNJuVj1VERnb166xIyZiBLUlempzfPr5LStpogajefPPKRf7JVc6wYKk/kNN9b4P7965na9szcv",
	"Pd+7RqXdrONhMAwoLmSGgmXcm3rHw2B4bNtlE1s7ja7HdQQWTZ5lO2Rfqr2QG5FIFunehhgGjHByuP7j",
	"wLIIrn91JMNOQrnY98tmVwM3wIXtJBASGVJbwwxNYmJrkYLptQONbJmFbOEodS7Fy8ibln3+27p1LpDg",
	"mYy2jiQVBoVdIMuyhIf23dFv2nXENZl+W92zQzFZ97fNdd7mlKBxerDL4Nuwd5u99ctRcHQHRasM7HAP",
	"k/Hp5DiYtFr9Ok1v/PuusahDehb5tkZbRxE0/RW1diGadxIEX8wDbWq9R7dnLKrrIbfTs6RoEpcy2hJc",
	"50LnWSYVoV+DESty3Wo8+XYaX8RVuJA+pW03TIOQBlaOkhA7+eTUPP12aj6XYpXw0DgqooYCrqsCqooA",
	"m87O+Y+/pfNfCtpsWAIa1TWqoqx1JFtUAFlR9NV426Lc7N6SpylT20Y2N6HPwtyOL6h1WWvavEo8nZOg",
	"FtJWU+yF2ucKmUEC2tYWUEVE2WBXsVIp5YM2CllqsZJZ9sqCMhTw2ixm9sAyZXCECZICNSI3ic824BYl",
	"2lcG3J1C8HYs+rOI+xmBLAwxMxgN4aIRKTY/Q+sxB395RtFF/YVUOykSYxKBkG5/MxJCmW1hwARgmpkt",
	"sPBKyE2C0RpT6j94QcKGTOPB8MEj6E6l3IDRB5P71k9F4js/fSbxqyBoZr6R+/O+ktNN/Kpd3pv4P0oF",
	"yMIYNDLqsank5mIn2QterZyomaX9OFDk/g5R4kOEdV1VALXbv/WVbr5hZAHowHvz362qbkm/GgS06a6+",
	"HXSHCLkfBgT3q7pKKuVy3uAiLstC68i2K80evnpERXjxc+LN71yPdYih2wxA7xOGF0f8QkLMVPGRgX5w",
	"SOIDF9cs4VF5FqOqG0UMvjt/9aWB5C72/ElYZVLa+y1h2SW//lEeilghkHBt7HlETafpHUy56GUlgQlp",
	"YlRdJrOBLhWE7EeXkcvV/SBzVrZTDDKF11zmOtlWB/1tmKuhpVWJlJp10cAJbxQDza+m9pDJ9ZBR31dV",
	"N/O/mql/rQ/a+eCpJ0pqZuUBtj4NfrPMqdoeVrPxt9PsnWC5iaXif1B91KOaY1dq4uUhFQ/1p2ytqq5F",
	"Q9kgbxJQl3OK3zr5XTTZj076Eq6ZZvfM+0Lg/sQvPoNqdAWuSHCHCD2cju1w9sKSrRXuQuL44LpCI2GJ",
	"VYr0UTdWv68AHncpRtZ/8KwdSN3unMZkaDclYCqM7UnmaqfIr8wXcYXkzW2T3V1yweydBlk6Dk5PH4/H",
	"T45OTk6efO5QqZc2aCpWO7Vfry9fCX0t/qn91d7tPV+RTI2YfIAE1C1QbLtFBqFUKs9M4cS/BT4/CPKp",
	"ZJ7wg62/7MkdrwuVB7WP7PvK6177SJEdzSOv2+F6z25i5yQVHcT2r8Lz7alUdVpuAT6W2rhzctKskL2X",
	"RNlzmNHbSxffvNeG8T/u63PqLniJZoMougvXtcRq4V2JJcO3T09r3Gq2WmTJ893Mb/4bAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
