// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for JobStatusKind.
const (
	Migrate  JobStatusKind = "migrate"
	Transfer JobStatusKind = "transfer"
)

// Valid indicates whether the value is a known member of the JobStatusKind enum.
func (e JobStatusKind) Valid() bool {
	switch e {
	case Migrate:
		return true
	case Transfer:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusState.
const (
	Failed    JobStatusState = "failed"
	Running   JobStatusState = "running"
	Succeeded JobStatusState = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatusState enum.
func (e JobStatusState) Valid() bool {
	switch e {
	case Failed:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// AttachResponse The outcome of attaching a partition.
type AttachResponse struct {
	// Partition The partition that was attached, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// ErrorResponse A structured error returned when a request cannot be fulfilled.
type ErrorResponse struct {
	// Code HTTP status code associated with the error
	Code *int32 `json:"code,omitempty"`

	// Error Error message describing the issue
	Error *string `json:"error,omitempty"`
}

// JobRef A reference to a background job started by the transfer or migrate endpoints.
type JobRef struct {
	// JobId Identifier of the started job
	JobId string `json:"job_id"`

	// StatusUrl Relative URL to poll for the job's status
	StatusUrl string `json:"status_url"`
}

// JobStatus The current state of a background transfer or migrate job.
type JobStatus struct {
	// Error A setup error that prevented the job from producing a per-day outcome, e.g. the source VictoriaLogs client could not be created
	Error *string `json:"error,omitempty"`

	// FinishedAt When the job reached a terminal state, as an RFC3339 timestamp; absent while the job is still running
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// JobId Identifier of the job
	JobId string `json:"job_id"`

	// Kind Which operation the job runs
	Kind JobStatusKind `json:"kind"`

	// Migrate The per-day and recent outcome, present once a migrate job has finished
	Migrate *MigrateResponse `json:"migrate,omitempty"`

	// StartedAt When the job started, as an RFC3339 timestamp
	StartedAt time.Time `json:"started_at"`

	// State Lifecycle state of the job; terminal states are succeeded and failed
	State JobStatusState `json:"state"`

	// Transfer The per-day outcome, present once a transfer job has finished
	Transfer *TransferResponse `json:"transfer,omitempty"`
}

// JobStatusKind Which operation the job runs
type JobStatusKind string

// JobStatusState Lifecycle state of the job; terminal states are succeeded and failed
type JobStatusState string

// MigrateRequest Parameters for a migrate request.
type MigrateRequest struct {
	// Range Inclusive time range whose sealed days will be migrated
	Range TimeRange `json:"range"`

	// TargetVlAuthKey Optional auth key for the target VictoriaLogs insert/select APIs, passed as the VictoriaLogs authKey
	TargetVlAuthKey *string `json:"target_vl_auth_key,omitempty"`

	// TargetVlbackupUrl Base URL of the target vlbackup instance, used to move sealed partitions (receive/attach)
	TargetVlbackupUrl string `json:"target_vlbackup_url"`

	// TargetVlinsertUrl Base URL of the target VictoriaLogs insert API, used to ingest today's data via the JSON stream API
	TargetVlinsertUrl string `json:"target_vlinsert_url"`

	// TargetVlselectUrl Base URL of the target VictoriaLogs select API, used to verify ingested row counts after migration
	TargetVlselectUrl string `json:"target_vlselect_url"`
}

// MigrateResponse The outcome of a migrate request.
type MigrateResponse struct {
	// Errors Per-day and recent-phase error messages
	Errors []string `json:"errors"`

	// Recent The outcome of copying today's (still-open) data
	Recent *RecentMigration `json:"recent,omitempty"`

	// Skipped Sealed partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Sealed partitions (YYYYMMDD) that were successfully moved
	Transferred []string `json:"transferred"`
}

// ReceiveResponse The outcome of receiving a partition snapshot.
type ReceiveResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition The partition that was received, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// RecentMigration The outcome of copying today's data as streamed JSONLine.
type RecentMigration struct {
	// BytesIngested Number of JSONLine bytes streamed to the target insert API
	BytesIngested int64 `json:"bytes_ingested"`

	// Partition Today's partition (YYYYMMDD) whose data was copied
	Partition string `json:"partition"`

	// SourceCount Row count for today on the source, from the verification query
	SourceCount int64 `json:"source_count"`

	// TargetCount Row count for today on the target, from the verification query
	TargetCount int64 `json:"target_count"`

	// Verified True when the target row count is at least the source row count
	Verified bool `json:"verified"`
}

// RestoreRequest Parameters for a restore request.
type RestoreRequest struct {
	// PartitionPrefix Partition to restore, formatted as YYYYMMDD
	PartitionPrefix string `json:"partition_prefix"`

	// SourceUrl Object Storage source URL to restore from, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	SourceUrl string `json:"source_url"`
}

// RestoreResponse The outcome of restoring a partition snapshot.
type RestoreResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition Array of partitions restored
	Partition []string `json:"partition"`
}

// SnapshotRequest Parameters for a snapshot request.
type SnapshotRequest struct {
	// DestinationUrl Object Storage destination URL, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	DestinationUrl string `json:"destination_url"`

	// Range Inclusive time range whose days will be snapshotted
	Range TimeRange `json:"range"`
}

// TimeRange An inclusive range of time. Each bound is a time expression of the form `<anchor>[+-<duration>][/<rounding>]`, where the anchor is `now` or an RFC3339 date, the optional duration is `<int><unit>` (e.g. `-7d`, `+12h`), and the optional `/<unit>` rounds the result down to that unit. Units: `y` (year), `M` (month), `w` (week, starts Monday), `d` (day), `h` (hour), `m` (minute), `s` (second). All math is performed in UTC.
type TimeRange struct {
	// From Start of the range, inclusive. A relative or absolute time expression (e.g. `now-7d/d`, `2024-01-01T00:00:00Z`).
	From string `json:"from"`

	// To End of the range, inclusive. A relative or absolute time expression (e.g. `now/d`, `2024-01-15T00:00:00Z`). Defaults to now.
	To *string `json:"to,omitempty"`
}

// TransferRequest Parameters for a transfer request.
type TransferRequest struct {
	// Range Inclusive time range whose days will be transferred
	Range TimeRange `json:"range"`

	// TargetUrl Base URL of the target vlbackup instance to transfer partitions to
	TargetUrl string `json:"target_url"`
}

// TransferResponse The outcome of a transfer request, per day.
type TransferResponse struct {
	// Errors Per-day error messages for partitions that failed to transfer
	Errors []string `json:"errors"`

	// Skipped Partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Partitions (YYYYMMDD) that were successfully transferred
	Transferred []string `json:"transferred"`
}

// JobIdPathParam defines model for JobIdPathParam.
type JobIdPathParam = string

// PartitionQueryParam defines model for PartitionQueryParam.
type PartitionQueryParam = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AttachSnapshotParams defines parameters for AttachSnapshot.
type AttachSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// ReceiveSnapshotParams defines parameters for ReceiveSnapshot.
type ReceiveSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// MigratePartitionsJSONRequestBody defines body for MigratePartitions for application/json ContentType.
type MigratePartitionsJSONRequestBody = MigrateRequest

// RestoreSnapshotJSONRequestBody defines body for RestoreSnapshot for application/json ContentType.
type RestoreSnapshotJSONRequestBody = RestoreRequest

// TriggerSnapshotJSONRequestBody defines body for TriggerSnapshot for application/json ContentType.
type TriggerSnapshotJSONRequestBody = SnapshotRequest

// TransferPartitionsJSONRequestBody defines body for TransferPartitions for application/json ContentType.
type TransferPartitionsJSONRequestBody = TransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the status of a transfer or migrate job
	// (GET /v1/vlbackup/jobs/{job_id})
	GetJob(w http.ResponseWriter, r *http.Request, jobId JobIdPathParam)
	// Migrate partitions and recent data to another vlbackup instance
	// (POST /v1/vlbackup/migrate)
	MigratePartitions(w http.ResponseWriter, r *http.Request)
	// Restore a partition from Object Storage
	// (POST /v1/vlbackup/restore)
	RestoreSnapshot(w http.ResponseWriter, r *http.Request)
	// Snapshot a range of partitions to Object Storage
	// (POST /v1/vlbackup/snapshot)
	TriggerSnapshot(w http.ResponseWriter, r *http.Request)
	// Transfer partitions to another vlbackup instance
	// (POST /v1/vlbackup/transfer)
	TransferPartitions(w http.ResponseWriter, r *http.Request)
	// Attach a received partition to VictoriaLogs
	// (POST /v1/vlbackup/transfer/attach)
	AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams)
	// Receive a snapshot from another vlbackup instance
	// (POST /v1/vlbackup/transfer/receive)
	ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get the status of a transfer or migrate job
// (GET /v1/vlbackup/jobs/{job_id})
func (_ Unimplemented) GetJob(w http.ResponseWriter, r *http.Request, jobId JobIdPathParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Migrate partitions and recent data to another vlbackup instance
// (POST /v1/vlbackup/migrate)
func (_ Unimplemented) MigratePartitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Restore a partition from Object Storage
// (POST /v1/vlbackup/restore)
func (_ Unimplemented) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Snapshot a range of partitions to Object Storage
// (POST /v1/vlbackup/snapshot)
func (_ Unimplemented) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transfer partitions to another vlbackup instance
// (POST /v1/vlbackup/transfer)
func (_ Unimplemented) TransferPartitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Attach a received partition to VictoriaLogs
// (POST /v1/vlbackup/transfer/attach)
func (_ Unimplemented) AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Receive a snapshot from another vlbackup instance
// (POST /v1/vlbackup/transfer/receive)
func (_ Unimplemented) ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "job_id" -------------
	var jobId JobIdPathParam

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", chi.URLParam(r, "job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "job_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, jobId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MigratePartitions operation middleware
func (siw *ServerInterfaceWrapper) MigratePartitions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MigratePartitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreSnapshot operation middleware
func (siw *ServerInterfaceWrapper) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreSnapshot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSnapshot operation middleware
func (siw *ServerInterfaceWrapper) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSnapshot(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferPartitions operation middleware
func (siw *ServerInterfaceWrapper) TransferPartitions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferPartitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachSnapshot operation middleware
func (siw *ServerInterfaceWrapper) AttachSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AttachSnapshotParams

	// ------------- Required query parameter "partition" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "partition", r.URL.Query(), &params.Partition, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "partition"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partition", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveSnapshot operation middleware
func (siw *ServerInterfaceWrapper) ReceiveSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveSnapshotParams

	// ------------- Required query parameter "partition" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "partition", r.URL.Query(), &params.Partition, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "partition"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "partition", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveSnapshot(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/vlbackup/jobs/{job_id}", wrapper.GetJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/migrate", wrapper.MigratePartitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/restore", wrapper.RestoreSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/snapshot", wrapper.TriggerSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer", wrapper.TransferPartitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer/attach", wrapper.AttachSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/vlbackup/transfer/receive", wrapper.ReceiveSnapshot)
	})

	return r
}

type GetJobRequestObject struct {
	JobId JobIdPathParam `json:"job_id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse JobStatus

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob404JSONResponse ErrorResponse

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type MigratePartitionsRequestObject struct {
	Body *MigratePartitionsJSONRequestBody
}

type MigratePartitionsResponseObject interface {
	VisitMigratePartitionsResponse(w http.ResponseWriter) error
}

type MigratePartitions202JSONResponse JobRef

func (response MigratePartitions202JSONResponse) VisitMigratePartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type MigratePartitions400JSONResponse ErrorResponse

func (response MigratePartitions400JSONResponse) VisitMigratePartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type MigratePartitions409JSONResponse ErrorResponse

func (response MigratePartitions409JSONResponse) VisitMigratePartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshotRequestObject struct {
	Body *RestoreSnapshotJSONRequestBody
}

type RestoreSnapshotResponseObject interface {
	VisitRestoreSnapshotResponse(w http.ResponseWriter) error
}

type RestoreSnapshot202JSONResponse RestoreResponse

func (response RestoreSnapshot202JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot400JSONResponse ErrorResponse

func (response RestoreSnapshot400JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot404JSONResponse ErrorResponse

func (response RestoreSnapshot404JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot409JSONResponse ErrorResponse

func (response RestoreSnapshot409JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RestoreSnapshot500JSONResponse ErrorResponse

func (response RestoreSnapshot500JSONResponse) VisitRestoreSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSnapshotRequestObject struct {
	Body *TriggerSnapshotJSONRequestBody
}

type TriggerSnapshotResponseObject interface {
	VisitTriggerSnapshotResponse(w http.ResponseWriter) error
}

type TriggerSnapshot202Response struct {
}

func (response TriggerSnapshot202Response) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerSnapshot400JSONResponse ErrorResponse

func (response TriggerSnapshot400JSONResponse) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerSnapshot500JSONResponse ErrorResponse

func (response TriggerSnapshot500JSONResponse) VisitTriggerSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitionsRequestObject struct {
	Body *TransferPartitionsJSONRequestBody
}

type TransferPartitionsResponseObject interface {
	VisitTransferPartitionsResponse(w http.ResponseWriter) error
}

type TransferPartitions202JSONResponse JobRef

func (response TransferPartitions202JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitions400JSONResponse ErrorResponse

func (response TransferPartitions400JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TransferPartitions409JSONResponse ErrorResponse

func (response TransferPartitions409JSONResponse) VisitTransferPartitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshotRequestObject struct {
	Params AttachSnapshotParams
}

type AttachSnapshotResponseObject interface {
	VisitAttachSnapshotResponse(w http.ResponseWriter) error
}

type AttachSnapshot200JSONResponse AttachResponse

func (response AttachSnapshot200JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot400JSONResponse ErrorResponse

func (response AttachSnapshot400JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot401JSONResponse ErrorResponse

func (response AttachSnapshot401JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AttachSnapshot500JSONResponse ErrorResponse

func (response AttachSnapshot500JSONResponse) VisitAttachSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshotRequestObject struct {
	Params ReceiveSnapshotParams
	Body   io.Reader
}

type ReceiveSnapshotResponseObject interface {
	VisitReceiveSnapshotResponse(w http.ResponseWriter) error
}

type ReceiveSnapshot200JSONResponse ReceiveResponse

func (response ReceiveSnapshot200JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot400JSONResponse ErrorResponse

func (response ReceiveSnapshot400JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot401JSONResponse ErrorResponse

func (response ReceiveSnapshot401JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot409JSONResponse ErrorResponse

func (response ReceiveSnapshot409JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveSnapshot500JSONResponse ErrorResponse

func (response ReceiveSnapshot500JSONResponse) VisitReceiveSnapshotResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get the status of a transfer or migrate job
	// (GET /v1/vlbackup/jobs/{job_id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// Migrate partitions and recent data to another vlbackup instance
	// (POST /v1/vlbackup/migrate)
	MigratePartitions(ctx context.Context, request MigratePartitionsRequestObject) (MigratePartitionsResponseObject, error)
	// Restore a partition from Object Storage
	// (POST /v1/vlbackup/restore)
	RestoreSnapshot(ctx context.Context, request RestoreSnapshotRequestObject) (RestoreSnapshotResponseObject, error)
	// Snapshot a range of partitions to Object Storage
	// (POST /v1/vlbackup/snapshot)
	TriggerSnapshot(ctx context.Context, request TriggerSnapshotRequestObject) (TriggerSnapshotResponseObject, error)
	// Transfer partitions to another vlbackup instance
	// (POST /v1/vlbackup/transfer)
	TransferPartitions(ctx context.Context, request TransferPartitionsRequestObject) (TransferPartitionsResponseObject, error)
	// Attach a received partition to VictoriaLogs
	// (POST /v1/vlbackup/transfer/attach)
	AttachSnapshot(ctx context.Context, request AttachSnapshotRequestObject) (AttachSnapshotResponseObject, error)
	// Receive a snapshot from another vlbackup instance
	// (POST /v1/vlbackup/transfer/receive)
	ReceiveSnapshot(ctx context.Context, request ReceiveSnapshotRequestObject) (ReceiveSnapshotResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, jobId JobIdPathParam) {
	var request GetJobRequestObject

	request.JobId = jobId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MigratePartitions operation middleware
func (sh *strictHandler) MigratePartitions(w http.ResponseWriter, r *http.Request) {
	var request MigratePartitionsRequestObject

	var body MigratePartitionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MigratePartitions(ctx, request.(MigratePartitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MigratePartitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MigratePartitionsResponseObject); ok {
		if err := validResponse.VisitMigratePartitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestoreSnapshot operation middleware
func (sh *strictHandler) RestoreSnapshot(w http.ResponseWriter, r *http.Request) {
	var request RestoreSnapshotRequestObject

	var body RestoreSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestoreSnapshot(ctx, request.(RestoreSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestoreSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestoreSnapshotResponseObject); ok {
		if err := validResponse.VisitRestoreSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerSnapshot operation middleware
func (sh *strictHandler) TriggerSnapshot(w http.ResponseWriter, r *http.Request) {
	var request TriggerSnapshotRequestObject

	var body TriggerSnapshotJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerSnapshot(ctx, request.(TriggerSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerSnapshotResponseObject); ok {
		if err := validResponse.VisitTriggerSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferPartitions operation middleware
func (sh *strictHandler) TransferPartitions(w http.ResponseWriter, r *http.Request) {
	var request TransferPartitionsRequestObject

	var body TransferPartitionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TransferPartitions(ctx, request.(TransferPartitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferPartitions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TransferPartitionsResponseObject); ok {
		if err := validResponse.VisitTransferPartitionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AttachSnapshot operation middleware
func (sh *strictHandler) AttachSnapshot(w http.ResponseWriter, r *http.Request, params AttachSnapshotParams) {
	var request AttachSnapshotRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AttachSnapshot(ctx, request.(AttachSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AttachSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AttachSnapshotResponseObject); ok {
		if err := validResponse.VisitAttachSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveSnapshot operation middleware
func (sh *strictHandler) ReceiveSnapshot(w http.ResponseWriter, r *http.Request, params ReceiveSnapshotParams) {
	var request ReceiveSnapshotRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveSnapshot(ctx, request.(ReceiveSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveSnapshotResponseObject); ok {
		if err := validResponse.VisitReceiveSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7d9s2lv8qONw5p/KGkijLSWz1jx6nnZlNNmkzjjN7WtsbQeSViJgEOABoRU393fdcAHxTtpyH6+40",
	"/8SWSPA+f/dJf/RCkWaCA9fKm330MippChqk+e2FWDyPXlMdv8aP8ZMIVChZppng3sx7HgHXbMlAErEk",
	"lCxoeLmSIucReS8WPqGKSNC55BCRxYboGIiWlKsl3iBJylaSaiDAo0wwpMD3GJ6bUR17vsdpCt7Mey8W",
	"71jk+Z6Ef+VMQuTNtMzB91QYQ0qRLPhA0yzBi6fL/cfBAQQHy8Ojg0k0PaJBGEyDx3C4H06nwcTzvZR+",
	"eAl8pWNvNt33vZTx+q8Z1RokUvG/Z8HwiA6XFx+n+9d/8XxPbzJ8hNKS8ZV3fe17r6nUDIXxjxzkZouU",
	"yosIMkS0ICIDw7jgPlkKmeIjI5TWzz///POrVz/8UAjiX3hsJYmsOGlHYewH+wfBZPK4yfRhg+fDBsvn",
	"59HHw15mr4tHGMs41pqG8QmoTHAFXZ5PYyAi16FIwZiGuZzxFaGkZGLk+V4mURaaQWF9jr/eA8uviY6p",
	"Jmuq3MEQbZfj15FGXf5nNbovykvF4j2E2rv2vb9KKeR2UR0TpWUe6lxCRACvrZxmHQMnlOCzQGkSUs6F",
	"JgsgyzxZsiSBqCvEUEQ9T/mv09PXRGmqc0XwCkKVEiGjKLA107FxTvN0z/esLL2Zx7ie7lt5sTRPvdnj",
	"oyMjL/vbJAhKfhnXsAKJDNtjOiQYOZAUlKIrIPa7BdoEPpoplUNTMwfB0ZOGciZN7zw/V+fnby7+s18/",
	"HTW8EIsTWPbJX8ISJPDQ+GYbxVBoUu8IYF1tOPC6BTrx4OI578WiYbb3iGi+Zy3kXS6TLsknkFDNroC8",
	"PXmJkspEkqDbGerfi8U3yhlYg/zx1WR8laBM82z8XizU+G4M7QcHh59uBXUvLeNIjcmLfkN5Y/noRaEw",
	"lxK4NrxCJ+71mcd7segaxhYnOSYKdJ45IDA4l0m4Ao6m4QRNllKkJJMiykOHqSCHEd0UkOsTGK1G1qpE",
	"LkMg/2ShFpLRl2KlSJgwZCAUeRIRByihBMSCL+aBvrdknKkYoneIJG02/weBrWBHgsFwQokGmTJOEytc",
	"k0BQTk7+9v10Oj0imqWgNE2zbwldKGRhHbMEynMYGiBLEiJzzpGKNvoPg8lw8vg0OJxN9mfT4Jc61EVU",
	"wxCf0BTBk4OGAPaDHk539/Hf1bcvGY/6NMHC2GUkNrQ6peTcODJHoD/zCrtGiqxZo+9UnNS+7zy4uGH2",
	"0aNJ8tPSm5199P4iEYy9/xhXCejYJRjjV/aGMmZeX/h96YAzesojIiFEeyjtP5NgDEQgqtO6J5KYKlLY",
	"poM8xN3bzdRduNUqbzC3IJgFX8zcjG90aX3JlhBuwgQqZHKUf9vyK0WoBKLyMASI0O94RJaUJcb9C4VX",
	"PlReiPTbyxqqr3/fIba0i52Vf+ru2FH721ReAnFX59vignGQQr4Nw+gLE6WRmtysN+13pZQJkpURumyu",
	"GxIk5as7eMkpS+HE3NKV0HMeJrnCYI02RszJZB0LBUQBTSAiEd0oska0XEBBmvEHTeUK9Lur5B3Ndfzu",
	"EjZd3n4yP9CE4CXkEjZlHmDvbsYbxhVIPVaQQKjJ8evnyicZVcrm6nhX43I8879h05cG7Bx8SiZs4tGf",
	"0DyjyiYzzlUc7cVNSLemPASf5EirFiQVV6UAy6RfkQHCD7uCsS1H9hpIEGudzcZje/iwOHx2GBwGdUBA",
	"Cm9NfLbzaWV8Jz57dITKqbhlfIVVhxYR3XyjSEQ1JVeMmjNevPnpRyxcgKZ4040c27NnRwf7h1+QY2tO",
	"n85xZY4Vx1cg2XLjGIeISLHGNIlrRehSQ5HS2Qp8O8P26C/CcAur+uy63wr6JeU7kLkR0HYt6m9HNJPF",
	"9uTRrzuhe5jFqDOo14imH6QhNQd8qbQ0pR+e2zMnAf4rL6FS0o1n5I0E7Y7DJ+b6V6Vl9MermuBCkW1M",
	"3esca2Cy1qHIgO8ZLzNR/pJlGfQkbG+68FO0O/ZcYwQwvNv7XSmQMqXwkRiIEgk02tTiZc1Ftkj8k5ok",
	"u8i6iNLyczjF/EOpZZ4kG4PQ0f1y0XbRGkuVGv3CF/o878SGj509z4abVjuNKE4zFYseN1xsNKh3a8m0",
	"hp7e2o95urA1irmQuAsRECOmLl2VBR+0pKEuGjbF01rtoicH9XbRURA8nRwd7T8+eHoQHB1Nar2j3s7R",
	"3RuALvI+mAag3xL2NnXXAeM2dbfxwgRiqlz4hcgE45eMwzbNF/HsJtUXZzgbKM/Woh5BqzTh3vTumK50",
	"XwMBm9EaeaAxhCJj1te+hs59zzZT3pmMoKc/ViQLNhkWpjrhtS6Mbxs3+IFJNFhoS+6iy//l5OlC/90J",
	"tTfeH6H2+D7LPJU52P53zfzKfIwwRagmCVBMUKs+V3lBpb6FEAlQvoPPlm7S0nRLnjWq+71baSHvUBdK",
	"e8P2LKqk9F0mYck+3DRi0qI4754RsZRZb0L+kxEPeaOFpKtSW66RXAgAjc7lKys1G48XeXgJemyZHmPu",
	"oqadjxv8mNvSzdBdUvadv3AWXuPU72rnRqPYOcLj9f9eEf4Y0ymksZbwOdNoYPpZ3Wzdj09Q6mXOt2Pm",
	"YI++dz+5MXu8Wybxxqlod7AplLodbSJQmnED+Dv5cu16dOiH6cD+PTXXGl21Qta6p+nYlvJNhXlFS9dn",
	"OGElNZYQsTRkjchfaRiThZlKYbS0xMIHrPsUKsv1RlCuZH6eB8E0pDyMhTQ/w9mjof0wym2eaj++OBvb",
	"j828i/GV+3juY7SWdhpjz8HHzrlYz03ZWXXMIzPbwetE0UcsnmFuseczru3R9tecM/f7nAyMic2HT6O5",
	"T+aPJvvxfM83zYTGofNx91ZDtW06SlB5okkk1txmuVQTvHRE3nKm1YzMN3My2ACVez6Zv5qTQSq4jvGX",
	"9ZwM1gCXvh0KKPJK8Ihu8KtoTgbux3hOBrHIze0p3s54rgF/U3MyUBAKHu2NyHGSkJTqGHnPQKI+ICKM",
	"k7en33fdE4NkT6mMZBQaNXbgV4YxIsdEFsNbVMVCiSTX0LEIJ1cu1sOn0dgIt5hjBJNTM8SYBcEv871R",
	"w2mL628cZUwb8DjgYv0bYuTB9RD/2y/+O7X/zRr/Dc7PR+fn0aO97wa//Hb2aHjR+HZvb3B+/tv5+W97",
	"3w3cl4/ONq/WUZyqi73vBuPaL/2ALHqWFXj0BcXZlOXkcUOW5AdY0jzRCq2Qi3VHuH9UybYgz1huL76V",
	"E59do1g53PmdZykNuK83fqoa7LMmDwaXCl5raZEW9zVi6O8/3xqx2jO823vJbZX6iIUo4Lt3lZtNZGMy",
	"ddkhzts5Zl28v0+veWuX9/X///bu67v0dZtd1T9QdxeVDGEumd68QbBx9RpQCfI4R1I74GC+I1pcAsfE",
	"wC5OohJDwZdsZRYFS3cpJrCe2880LQ9zQsUt4oNd4WR82RPsjl8/t3KPKY8SUFXmyvjKr2Rv6lEzsimq",
	"08ZErXIy9FnNtAGnf758ZkHNNg2vQCr71MkoGAWoApEBpxnzZt50FIympqbWsZFTd3vsox3XX+O3aNE9",
	"a2o6l9ymeDfvat11u8/lAJj0EqZVewXBbh4w7faZVGefaUReiIVdvoghMSleCqmQdg6GHydCGY9FAVNp",
	"wlq5mfM88mbe30G/MDtE9UXtLbGtumTcWuTGGCcdNBsx7weBXR3luhh9ZVni2n7j98qW62XA+dhc7tq2",
	"W1XsRe2y5mSXk+prRPW9nG3rNG4VprmCUts4KSLF2UUNasv+wb5x1zpElV9Nq9bCgXdRLT/joTflEdXu",
	"oHG3HbYHi7Wwa987CA520MJuhDSXjnuI+VEY+4cPTGlVrQCv2BVwwmzBqvI0pXJj7a5YUtW5akXs5qqj",
	"aZeuVGNpzEiw4cu1nbBM9OV8L9ll5Y4+WeSa0ESJ4knWv1P0F7f71ZmijsjfhCToi7WdF3Q6W/yZLAMi",
	"l88xbUaH9tis3k7ty88GBUD6blDikwg0DWPfbaTvjchzIzFuhxKqObxZbGwvvQD2RIQ0aYKpuAJJ8Kd/",
	"vOyd9RjMsB1ri0eE8Qa136j2ksaInNaJYMXAhAxqHXSmSAJLcxoN9V79MbY8p3po2u5DhLuZ6V8PZY6Y",
	"NbTToYpXKdbKJ4rx9gZqJECZzdMIotyaOMKne1AX9txqQpUxuBcgQOlnItp8Ma9p7XT1uM2r5soDqeFw",
	"+52M6w7I7t8NZO+Cn/XF7U/Zub4Lwp3Acrto0EpoGEKm3WZhEWGp6kTfEanusd7X3a3CI3pcyCdKoNGH",
	"lBO0vqUBIZ4jMghJEsFXmBxhFZ/rhBWerSVbrcCkLk6DM7vHbjHBvXbhUA4LNFM8SLHCmr7sMC1NTN++",
	"fzqyaB7cH5o/o1FVONmSgCauk7QQ0QZTlyuasALuhCw/cNj29uSlpfro/qg+3hZDDM64QsYton5LBE82",
	"RHAwq8mEatfSbEWqwkFbJuQUZIBPC0K50DHIbsW9W/Rys4Pt0esHseaJoJHqnd+QAUWxj1a/7lWTVoe/",
	"re66bYT7xWxGNYDehg3DE2bMNo20b0SZC7VowG4XV91Y6k016fkaqNqaiPYYwklzBPpVUbU1KjuYHB1M",
	"g4PGZKqa9+wMi+0BXw+Tb6rRi5081fUVNcrdB4cf6J85V3mWCQPmtQGuqzrvO389bSRxpWetqU0slnbu",
	"wVv+dO8Q973gy4SF2m8lljWAKy3AuLNV/uP7VP5zrkGaKhUkZp22f2ZnwpEDMtddqir/xoS4CcGFN9eh",
	"z8BcSxcV1BZ42kXa8hFboXb3JN93bzkhKDdXgQvrcfWYxdWS+CLJN5hq0hgL3kV1UJ+AboFv9PQIEigK",
	"F/uE+jy/CcynNk/5ysDcHh/fDFqfCs23HFgki25g2aNF23Cnqj5QNRLNMzRNiL61jfhYJMZOuXArclWf",
	"lAwoJ5BmelPUe+YdHvsJDS+5WCcQrSAFrvdGDx5+WzP3GgY/GOAwruZQw+rpFtQoDYNWg+zGyGM7fJQn",
	"dvGj3g36fPwoHqRuhYn+xkHRJrDpmcN7mwaoS1W/A3NUExcI64UHy9VXL4jbo7m+QNwa3PxZEvfIZveK",
	"uFYTFeaU5olmw78/QyjAOtiUxDfVvUVx/NVL3z/r3d+93j3tHQ9/boFbfOXeaNuOnsdFuUnNe+pM5CrZ",
	"lFv53U5qT6ezoKwLc/bwWhJ0t6lH319n+fzRx+fVia0/nNJjJNUu7wMsDWuD5sKfKnkYyib3R9lbTnMd",
	"C8l+haiXNDsHrUakDyk/qv4kTqMwbAyMjZHXR8VnF2i/lfNbazI9+D6Hq7vZHf3eHbjd8d07S7VqyA0a",
	"zGyop+dlKsCtsGQCzC5NLp9YmNSCLKB0kb7WlqHvK4DHLlnW6leWNQ2p273Aa7A00VQSKsPYrJMtW32C",
	"UnwRk4DabLx/sWCcytab0pPg6OjxZPJk/+nTp09u2+7pbavUCauU2k/XDile8DD6c81X7G4udZ0z1Wzy",
	"ATboboBi32wCkVBImWfaKfEPgc8PojlXpGJuOG5WqFiVqDyoOLLtpY07xRHnHfX3A26G6y3RxDwTSbQQ",
	"28+F53u2JnNriwbgY6G0XVhEytzZW3tHW9aOepsE7m/nVYLxP26r0qryfgF6DcC7jKvqxJLx7olFB3Qb",
	"nUa45dOqI4s+6PXF9f8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
