// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for JobStatusKind.
const (
	Migrate  JobStatusKind = "migrate"
	Transfer JobStatusKind = "transfer"
)

// Valid indicates whether the value is a known member of the JobStatusKind enum.
func (e JobStatusKind) Valid() bool {
	switch e {
	case Migrate:
		return true
	case Transfer:
		return true
	default:
		return false
	}
}

// Defines values for JobStatusState.
const (
	Failed    JobStatusState = "failed"
	Running   JobStatusState = "running"
	Succeeded JobStatusState = "succeeded"
)

// Valid indicates whether the value is a known member of the JobStatusState enum.
func (e JobStatusState) Valid() bool {
	switch e {
	case Failed:
		return true
	case Running:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// AttachResponse The outcome of attaching a partition.
type AttachResponse struct {
	// Partition The partition that was attached, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// ErrorResponse A structured error returned when a request cannot be fulfilled.
type ErrorResponse struct {
	// Code HTTP status code associated with the error
	Code *int32 `json:"code,omitempty"`

	// Error Error message describing the issue
	Error *string `json:"error,omitempty"`
}

// JobRef A reference to a background job started by the transfer or migrate endpoints.
type JobRef struct {
	// JobId Identifier of the started job
	JobId string `json:"job_id"`

	// StatusUrl Relative URL to poll for the job's status
	StatusUrl string `json:"status_url"`
}

// JobStatus The current state of a background transfer or migrate job.
type JobStatus struct {
	// Error A setup error that prevented the job from producing a per-day outcome, e.g. the source VictoriaLogs client could not be created
	Error *string `json:"error,omitempty"`

	// FinishedAt When the job reached a terminal state, as an RFC3339 timestamp; absent while the job is still running
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// JobId Identifier of the job
	JobId string `json:"job_id"`

	// Kind Which operation the job runs
	Kind JobStatusKind `json:"kind"`

	// Migrate The per-day and recent outcome, present once a migrate job has finished
	Migrate *MigrateResponse `json:"migrate,omitempty"`

	// StartedAt When the job started, as an RFC3339 timestamp
	StartedAt time.Time `json:"started_at"`

	// State Lifecycle state of the job; terminal states are succeeded and failed
	State JobStatusState `json:"state"`

	// Transfer The per-day outcome, present once a transfer job has finished
	Transfer *TransferResponse `json:"transfer,omitempty"`
}

// JobStatusKind Which operation the job runs
type JobStatusKind string

// JobStatusState Lifecycle state of the job; terminal states are succeeded and failed
type JobStatusState string

// MigrateRequest Parameters for a migrate request.
type MigrateRequest struct {
	// Range Inclusive time range whose sealed days will be migrated
	Range TimeRange `json:"range"`

	// TargetVlAuthKey Optional auth key for the target VictoriaLogs insert/select APIs, passed as the VictoriaLogs authKey
	TargetVlAuthKey *string `json:"target_vl_auth_key,omitempty"`

	// TargetVlbackupUrl Base URL of the target vlbackup instance, used to move sealed partitions (receive/attach)
	TargetVlbackupUrl string `json:"target_vlbackup_url"`

	// TargetVlinsertUrl Base URL of the target VictoriaLogs insert API, used to ingest today's data via the JSON stream API
	TargetVlinsertUrl string `json:"target_vlinsert_url"`

	// TargetVlselectUrl Base URL of the target VictoriaLogs select API, used to verify ingested row counts after migration
	TargetVlselectUrl string `json:"target_vlselect_url"`
}

// MigrateResponse The outcome of a migrate request.
type MigrateResponse struct {
	// Errors Per-day and recent-phase error messages
	Errors []string `json:"errors"`

	// Recent The outcome of copying today's (still-open) data
	Recent *RecentMigration `json:"recent,omitempty"`

	// Skipped Sealed partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Sealed partitions (YYYYMMDD) that were successfully moved
	Transferred []string `json:"transferred"`
}

// ReceiveResponse The outcome of receiving a partition snapshot.
type ReceiveResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition The partition that was received, formatted as YYYYMMDD
	Partition string `json:"partition"`
}

// RecentMigration The outcome of copying today's data as streamed JSONLine.
type RecentMigration struct {
	// BytesIngested Number of JSONLine bytes streamed to the target insert API
	BytesIngested int64 `json:"bytes_ingested"`

	// Partition Today's partition (YYYYMMDD) whose data was copied
	Partition string `json:"partition"`

	// SourceCount Row count for today on the source, from the verification query
	SourceCount int64 `json:"source_count"`

	// TargetCount Row count for today on the target, from the verification query
	TargetCount int64 `json:"target_count"`

	// Verified True when the target row count is at least the source row count
	Verified bool `json:"verified"`
}

// RestoreRequest Parameters for a restore request.
type RestoreRequest struct {
	// PartitionPrefix Partition to restore, formatted as YYYYMMDD
	PartitionPrefix string `json:"partition_prefix"`

	// SourceUrl Object Storage source URL to restore from, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	SourceUrl string `json:"source_url"`
}

// RestoreResponse The outcome of restoring a partition snapshot.
type RestoreResponse struct {
	// BytesWritten Number of bytes written to disk while extracting the snapshot
	BytesWritten int64 `json:"bytes_written"`

	// Partition Array of partitions restored
	Partition []string `json:"partition"`
}

// SnapshotRequest Parameters for a snapshot request.
type SnapshotRequest struct {
	// DestinationUrl Object Storage destination URL, e.g. gs://bucket/prefix/ or s3://bucket/prefix/
	DestinationUrl string `json:"destination_url"`

	// Range Inclusive time range whose days will be snapshotted
	Range TimeRange `json:"range"`
}

// TimeRange An inclusive range of time. Each bound is a time expression of the form `<anchor>[+-<duration>][/<rounding>]`, where the anchor is `now` or an RFC3339 date, the optional duration is `<int><unit>` (e.g. `-7d`, `+12h`), and the optional `/<unit>` rounds the result down to that unit. Units: `y` (year), `M` (month), `w` (week, starts Monday), `d` (day), `h` (hour), `m` (minute), `s` (second). All math is performed in UTC.
type TimeRange struct {
	// From Start of the range, inclusive. A relative or absolute time expression (e.g. `now-7d/d`, `2024-01-01T00:00:00Z`).
	From string `json:"from"`

	// To End of the range, inclusive. A relative or absolute time expression (e.g. `now/d`, `2024-01-15T00:00:00Z`). Defaults to now.
	To *string `json:"to,omitempty"`
}

// TransferRequest Parameters for a transfer request.
type TransferRequest struct {
	// Range Inclusive time range whose days will be transferred
	Range TimeRange `json:"range"`

	// TargetUrl Base URL of the target vlbackup instance to transfer partitions to
	TargetUrl string `json:"target_url"`
}

// TransferResponse The outcome of a transfer request, per day.
type TransferResponse struct {
	// Errors Per-day error messages for partitions that failed to transfer
	Errors []string `json:"errors"`

	// Skipped Partitions (YYYYMMDD) that were skipped, e.g. missing or already present on the target
	Skipped []string `json:"skipped"`

	// Transferred Partitions (YYYYMMDD) that were successfully transferred
	Transferred []string `json:"transferred"`
}

// JobIdPathParam defines model for JobIdPathParam.
type JobIdPathParam = string

// PartitionQueryParam defines model for PartitionQueryParam.
type PartitionQueryParam = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// AttachSnapshotParams defines parameters for AttachSnapshot.
type AttachSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// ReceiveSnapshotParams defines parameters for ReceiveSnapshot.
type ReceiveSnapshotParams struct {
	// Partition Partition name to operate on, formatted as YYYYMMDD
	Partition PartitionQueryParam `form:"partition" json:"partition"`
}

// MigratePartitionsJSONRequestBody defines body for MigratePartitions for application/json ContentType.
type MigratePartitionsJSONRequestBody = MigrateRequest

// RestoreSnapshotJSONRequestBody defines body for RestoreSnapshot for application/json ContentType.
type RestoreSnapshotJSONRequestBody = RestoreRequest

// TriggerSnapshotJSONRequestBody defines body for TriggerSnapshot for application/json ContentType.
type TriggerSnapshotJSONRequestBody = SnapshotRequest

// TransferPartitionsJSONRequestBody defines body for TransferPartitions for application/json ContentType.
type TransferPartitionsJSONRequestBody = TransferRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetJob request
	GetJob(ctx context.Context, jobId JobIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MigratePartitionsWithBody request with any body
	MigratePartitionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	MigratePartitions(ctx context.Context, body MigratePartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RestoreSnapshotWithBody request with any body
	RestoreSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RestoreSnapshot(ctx context.Context, body RestoreSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TriggerSnapshotWithBody request with any body
	TriggerSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TriggerSnapshot(ctx context.Context, body TriggerSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TransferPartitionsWithBody request with any body
	TransferPartitionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TransferPartitions(ctx context.Context, body TransferPartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AttachSnapshot request
	AttachSnapshot(ctx context.Context, params *AttachSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReceiveSnapshotWithBody request with any body
	ReceiveSnapshotWithBody(ctx context.Context, params *ReceiveSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetJob(ctx context.Context, jobId JobIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MigratePartitionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMigratePartitionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MigratePartitions(ctx context.Context, body MigratePartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMigratePartitionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestoreSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestoreSnapshotRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestoreSnapshot(ctx context.Context, body RestoreSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestoreSnapshotRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TriggerSnapshotWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTriggerSnapshotRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TriggerSnapshot(ctx context.Context, body TriggerSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTriggerSnapshotRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TransferPartitionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTransferPartitionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TransferPartitions(ctx context.Context, body TransferPartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTransferPartitionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AttachSnapshot(ctx context.Context, params *AttachSnapshotParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAttachSnapshotRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReceiveSnapshotWithBody(ctx context.Context, params *ReceiveSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReceiveSnapshotRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetJobRequest generates requests for GetJob
func NewGetJobRequest(server string, jobId JobIdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMigratePartitionsRequest calls the generic MigratePartitions builder with application/json body
func NewMigratePartitionsRequest(server string, body MigratePartitionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMigratePartitionsRequestWithBody(server, "application/json", bodyReader)
}

// NewMigratePartitionsRequestWithBody generates requests for MigratePartitions with any type of body
func NewMigratePartitionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/migrate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRestoreSnapshotRequest calls the generic RestoreSnapshot builder with application/json body
func NewRestoreSnapshotRequest(server string, body RestoreSnapshotJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRestoreSnapshotRequestWithBody(server, "application/json", bodyReader)
}

// NewRestoreSnapshotRequestWithBody generates requests for RestoreSnapshot with any type of body
func NewRestoreSnapshotRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/restore")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTriggerSnapshotRequest calls the generic TriggerSnapshot builder with application/json body
func NewTriggerSnapshotRequest(server string, body TriggerSnapshotJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTriggerSnapshotRequestWithBody(server, "application/json", bodyReader)
}

// NewTriggerSnapshotRequestWithBody generates requests for TriggerSnapshot with any type of body
func NewTriggerSnapshotRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/snapshot")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTransferPartitionsRequest calls the generic TransferPartitions builder with application/json body
func NewTransferPartitionsRequest(server string, body TransferPartitionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTransferPartitionsRequestWithBody(server, "application/json", bodyReader)
}

// NewTransferPartitionsRequestWithBody generates requests for TransferPartitions with any type of body
func NewTransferPartitionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/transfer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAttachSnapshotRequest generates requests for AttachSnapshot
func NewAttachSnapshotRequest(server string, params *AttachSnapshotParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/transfer/attach")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "partition", params.Partition, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReceiveSnapshotRequestWithBody generates requests for ReceiveSnapshot with any type of body
func NewReceiveSnapshotRequestWithBody(server string, params *ReceiveSnapshotParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/vlbackup/transfer/receive")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "partition", params.Partition, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetJobWithResponse request
	GetJobWithResponse(ctx context.Context, jobId JobIdPathParam, reqEditors ...RequestEditorFn) (*GetJobResponse, error)

	// MigratePartitionsWithBodyWithResponse request with any body
	MigratePartitionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MigratePartitionsResponse, error)

	MigratePartitionsWithResponse(ctx context.Context, body MigratePartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*MigratePartitionsResponse, error)

	// RestoreSnapshotWithBodyWithResponse request with any body
	RestoreSnapshotWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestoreSnapshotResponse, error)

	RestoreSnapshotWithResponse(ctx context.Context, body RestoreSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*RestoreSnapshotResponse, error)

	// TriggerSnapshotWithBodyWithResponse request with any body
	TriggerSnapshotWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TriggerSnapshotResponse, error)

	TriggerSnapshotWithResponse(ctx context.Context, body TriggerSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*TriggerSnapshotResponse, error)

	// TransferPartitionsWithBodyWithResponse request with any body
	TransferPartitionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TransferPartitionsResponse, error)

	TransferPartitionsWithResponse(ctx context.Context, body TransferPartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*TransferPartitionsResponse, error)

	// AttachSnapshotWithResponse request
	AttachSnapshotWithResponse(ctx context.Context, params *AttachSnapshotParams, reqEditors ...RequestEditorFn) (*AttachSnapshotResponse, error)

	// ReceiveSnapshotWithBodyWithResponse request with any body
	ReceiveSnapshotWithBodyWithResponse(ctx context.Context, params *ReceiveSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReceiveSnapshotResponse, error)
}

type GetJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobStatus
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MigratePartitionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *JobRef
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r MigratePartitionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MigratePartitionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MigratePartitionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RestoreSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *RestoreResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RestoreSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RestoreSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RestoreSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TriggerSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r TriggerSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TriggerSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TriggerSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TransferPartitionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *JobRef
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r TransferPartitionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TransferPartitionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TransferPartitionsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AttachSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AttachResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r AttachSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AttachSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AttachSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReceiveSnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReceiveResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReceiveSnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReceiveSnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReceiveSnapshotResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetJobWithResponse request returning *GetJobResponse
func (c *ClientWithResponses) GetJobWithResponse(ctx context.Context, jobId JobIdPathParam, reqEditors ...RequestEditorFn) (*GetJobResponse, error) {
	rsp, err := c.GetJob(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobResponse(rsp)
}

// MigratePartitionsWithBodyWithResponse request with arbitrary body returning *MigratePartitionsResponse
func (c *ClientWithResponses) MigratePartitionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MigratePartitionsResponse, error) {
	rsp, err := c.MigratePartitionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMigratePartitionsResponse(rsp)
}

func (c *ClientWithResponses) MigratePartitionsWithResponse(ctx context.Context, body MigratePartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*MigratePartitionsResponse, error) {
	rsp, err := c.MigratePartitions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMigratePartitionsResponse(rsp)
}

// RestoreSnapshotWithBodyWithResponse request with arbitrary body returning *RestoreSnapshotResponse
func (c *ClientWithResponses) RestoreSnapshotWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestoreSnapshotResponse, error) {
	rsp, err := c.RestoreSnapshotWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestoreSnapshotResponse(rsp)
}

func (c *ClientWithResponses) RestoreSnapshotWithResponse(ctx context.Context, body RestoreSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*RestoreSnapshotResponse, error) {
	rsp, err := c.RestoreSnapshot(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestoreSnapshotResponse(rsp)
}

// TriggerSnapshotWithBodyWithResponse request with arbitrary body returning *TriggerSnapshotResponse
func (c *ClientWithResponses) TriggerSnapshotWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TriggerSnapshotResponse, error) {
	rsp, err := c.TriggerSnapshotWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTriggerSnapshotResponse(rsp)
}

func (c *ClientWithResponses) TriggerSnapshotWithResponse(ctx context.Context, body TriggerSnapshotJSONRequestBody, reqEditors ...RequestEditorFn) (*TriggerSnapshotResponse, error) {
	rsp, err := c.TriggerSnapshot(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTriggerSnapshotResponse(rsp)
}

// TransferPartitionsWithBodyWithResponse request with arbitrary body returning *TransferPartitionsResponse
func (c *ClientWithResponses) TransferPartitionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TransferPartitionsResponse, error) {
	rsp, err := c.TransferPartitionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransferPartitionsResponse(rsp)
}

func (c *ClientWithResponses) TransferPartitionsWithResponse(ctx context.Context, body TransferPartitionsJSONRequestBody, reqEditors ...RequestEditorFn) (*TransferPartitionsResponse, error) {
	rsp, err := c.TransferPartitions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTransferPartitionsResponse(rsp)
}

// AttachSnapshotWithResponse request returning *AttachSnapshotResponse
func (c *ClientWithResponses) AttachSnapshotWithResponse(ctx context.Context, params *AttachSnapshotParams, reqEditors ...RequestEditorFn) (*AttachSnapshotResponse, error) {
	rsp, err := c.AttachSnapshot(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAttachSnapshotResponse(rsp)
}

// ReceiveSnapshotWithBodyWithResponse request with arbitrary body returning *ReceiveSnapshotResponse
func (c *ClientWithResponses) ReceiveSnapshotWithBodyWithResponse(ctx context.Context, params *ReceiveSnapshotParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReceiveSnapshotResponse, error) {
	rsp, err := c.ReceiveSnapshotWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReceiveSnapshotResponse(rsp)
}

// ParseGetJobResponse parses an HTTP response from a GetJobWithResponse call
func ParseGetJobResponse(rsp *http.Response) (*GetJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseMigratePartitionsResponse parses an HTTP response from a MigratePartitionsWithResponse call
func ParseMigratePartitionsResponse(rsp *http.Response) (*MigratePartitionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MigratePartitionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JobRef
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseRestoreSnapshotResponse parses an HTTP response from a RestoreSnapshotWithResponse call
func ParseRestoreSnapshotResponse(rsp *http.Response) (*RestoreSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RestoreSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest RestoreResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTriggerSnapshotResponse parses an HTTP response from a TriggerSnapshotWithResponse call
func ParseTriggerSnapshotResponse(rsp *http.Response) (*TriggerSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TriggerSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTransferPartitionsResponse parses an HTTP response from a TransferPartitionsWithResponse call
func ParseTransferPartitionsResponse(rsp *http.Response) (*TransferPartitionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TransferPartitionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JobRef
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseAttachSnapshotResponse parses an HTTP response from a AttachSnapshotWithResponse call
func ParseAttachSnapshotResponse(rsp *http.Response) (*AttachSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AttachSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AttachResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseReceiveSnapshotResponse parses an HTTP response from a ReceiveSnapshotWithResponse call
func ParseReceiveSnapshotResponse(rsp *http.Response) (*ReceiveSnapshotResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReceiveSnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReceiveResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
