---
on:
  pull_request:
    paths:
      - '**/*.toml'
      - .github/workflows/lint-toml.yaml
name: Lint TOML files
concurrency:
  group: lint-toml-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  fmt-toml:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c  # v4.3.0
        with:
          install: true
      - name: Lint markdown files on changed files
        run: |-
          files=$(git diff --name-only --diff-filter=ACMR "${{ github.event.pull_request.base.sha }}"..."${{ github.sha }}" | grep -E '\.md$' || true)
          if [ -z "$files" ]; then
            echo "No TOML files changed"
          else
            echo "Changed TOML files:"
            echo "$files"
            mise exec -- tombi format --check $files
          fi
  lint-toml:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c  # v4.3.0
        with:
          install: true
      - name: Lint markdown files on changed files
        run: |-
          files=$(git diff --name-only --diff-filter=ACMR "${{ github.event.pull_request.base.sha }}"..."${{ github.sha }}" | grep -E '\.md$' || true)
          if [ -z "$files" ]; then
            echo "No TOML files changed"
          else
            echo "Changed TOML files:"
            echo "$files"
            mise exec -- tombi lint $files
          fi
